### ISSUE TITLE
Add GitHub actions to enforce code style

### ISSUE THREAD

**Issue by lacabra** [lacabra/submission-digitalpublicgoods#15]
After having implemented #14, configure the CI through GitHub Actions to enforce the code style upon committing files to the repo.

**Comment by rachita19082** [comment]
@lacabra I would like to work on this issue. Please assign it to me.

**Comment by DivyanshiSingh** [comment]
hey, @lacabra Is this issue open to work. I would like to work on it.

**Comment by rachita19082** [comment]
Hi @DivyanshiSingh, even though this has not been assigned to me yet, I had started working on this issue. I will make a PR for this as soon as my previous pull request for adding and configuring the setup is merged.

**Comment by DivyanshiSingh** [comment]
I thought that everyone has to follow the guidelines: https://github.com/unicef/publicgoods-candidates/issues/473

**Comment by rachita19082** [comment]
@DivyanshiSingh Yes, I have followed all the guidelines. I claimed this issue only after I had finished working on the previous issue and the previous one has been approved as well.

**Comment by lacabra** [comment]
@rachita19082: while I appreciate your numerous contributions, I had **not** assigned this PR to you for a reason: to give the rest of participants a fair chance to contribute. Everyone else is waiting for PR to get assigned to them, so kindly play by the rules. Thank you.

**Comment by rachita19082** [comment]
@lacabra I apologize for not waiting for the PR to be assigned. I have understood, I will wait for it to be assigned before working on any further issues.
