### ISSUE TITLE
Split DPG Full Submissions into Two Different Pull Requests

### ISSUE THREAD

**Issue by nathanbaleeta** [lacabra/submission-digitalpublicgoods#30]
The current [submission form](https://submission.digitalpublicgoods.net/) create a single pull request with two files, one that lives in `nominees/` and another in `digitalpublicgoods/`. This creates a challenge where if a project is successfully nominated and reviewed, the nomination-only part  of this PR cannot be merged by itself without merging the full submission. 

In order to match out workflows, modifying the submission form to open two different pull requests seems to be the best alternative at hand for now. This issue addresses the above challenges.

**Comment by nathanfletcher** [comment]
I submitted a pull request to fix this here https://github.com/lacabra/submission-digitalpublicgoods/pull/33

**Comment by lacabra** [comment]
Fixed in #35
