### ISSUE TITLE
Privacy & Security Question Bug 

### ISSUE THREAD

**Issue by Lucyeoh** [lacabra/submission-digitalpublicgoods#46]
I was looking through the form today and I found a bug on the questions for indicator 9a re: PII data. 
& 1) It didn’t ask about sharing third party data as listed in the [questionary](https://github.com/DPGAlliance/DPG-Standard/blob/main/standard-questions.md) “If yes - does this project share this data with third parties? Please describe the circumstances with which this project shares data with third parties. Please add links as relevant.” 

2) appears to cut off the question about ensuring security and privacy (see image)
<img width="511" alt="Screen Shot 2021-07-28 at 11 45 36 AM" src="https://user-images.githubusercontent.com/66376240/127355081-08c75d31-b0bf-48fa-8f6e-61f888736903.png">

**Comment by nathanfletcher** [comment]
Hi @Lucyeoh I'm on it. I am a bit unclear as to how it should look like. I will add ```“If yes - does this project share this data with third parties? Please describe the circumstances with which this project shares data with third parties. Please add links as relevant.”``` to the description below and send a screenshot. However, if there's anything else from that section of the [questionary](https://github.com/DPGAlliance/DPG-Standard/blob/main/standard-questions.md) I should include, please let me know.

**Comment by lacabra** [comment]
Yes, @nathanbaleeta it should align with the questionary that you are linking, and also please make sure that if you are making any changes to the [data schema](https://github.com/lacabra/submission-digitalpublicgoods/blob/main/schemas/schema.js), that it aligns with the [data schema](https://github.com/unicef/publicgoods-candidates/blob/main/screening-schema.json) on the receiving end.

**Comment by nathanfletcher** [comment]
@Lucyeoh This is the screenshot. cc @lacabra 
![Web capture_28-7-2021_172217_localhost](https://user-images.githubusercontent.com/1917416/127368103-18afbfd6-644a-4cf6-a211-be05f8c6b0da.jpeg)
